POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFuZ2VsQGdtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MjMzODM5MTMsImV4cCI6MTcyMzQ3MDMxM30.Fsr6oq6Bxw72SjX60b-ivyuwGwK7YCtYiFKNWTpwmeM

{
  "author": "Daasd",
  "title": "Reaasd",
  "url": "rea.org",
  "year": 2020
}